nameOverride: ""
fullnameOverride: ""

image:
  registry: ghcr.io
  repository: sun-asterisk-research/keda-redis-scaler
  tag: ""
  pullPolicy: IfNotPresent
  pullSecrets: []

replicaCount: 1

logLevel: info

extraEnvVars: []

podAnnotations: {}

podSecurityContext:
  enabled: false
  # fsGroup: 2000

containerSecurityContext:
  enabled: false
  # capabilities:
  #   drop:
  #   - ALL
  # readOnlyRootFilesystem: true
  # runAsNonRoot: true
  # runAsUser: 1000

resources: {}
  # limits:
  #   cpu: 100m
  #   memory: 128Mi
  # requests:
  #   cpu: 100m
  #   memory: 128Mi

podAffinityPreset: ""

podAntiAffinityPreset: soft

nodeAffinityPreset:
  type: ""
  key: ""
  values: []

nodeSelector: {}

tolerations: []

affinity: {}

topologySpreadConstraints: []

service:
  type: ClusterIP
  port: 9000
