name: Release chart

permissions:
  contents: read
  packages: write

on:
  push:
    paths:
    - .github/workflows/release-chart.yml
    - charts/**
    branches:
    - master
  pull_request:

jobs:
  chart-release:
    name: Release chart
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Login to GHCR
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.repository_owner }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Setup Helm
      uses: azure/setup-helm@v3

    - name: Get chart version
      id: chart_version
      uses: mikefarah/yq@master
      with:
        cmd: yq '.version' 'charts/keda-redis-scaler/Chart.yaml'

    - name: Check existing chart
      id: check_existing_chart
      run: |
        helm show chart oci://ghcr.io/${{ github.repository_owner }}/helm-charts/keda-redis-scaler --version=${{ steps.chart_version.outputs.result }}
      continue-on-error: true

    - name: Push chart
      if: steps.check_existing_chart.outcome == 'failure'
      run: |
        helm dependency update charts/keda-redis-scaler
        helm package charts/keda-redis-scaler --destination .deploy
        helm push "keda-redis-scaler-${{ steps.chart_version.outputs.result }}" oci://ghcr.io/${{ github.repository_owner }}/helm-charts
